batch_size: 32
lr: 0.01
env: FlappyBird-v0
gamma: 0.99
sync_rate: 1000
replay_size: 100000
warm_start_size: 10000
eps_start: 1.0
eps_end: 0.02
eps_last_frame: 15000
episode_length: 1000
warm_start_steps: 10000
