batch_size: 32
lr: 0.1
env: FlappyBird-v0
size_hidden_layers: 512
gamma: 1.0
sync_rate: 1000
replay_size: 5000
warm_start_size: 5000
eps_start: 1.0
eps_end: 0.02
eps_last_frame: 15000
episode_length: 5000
warm_start_steps: 5000
